### ISSUE TITLE
Im having a problem syncing the daemon to the nework.

### ISSUE THREAD

**Issue by NotYourTypicalPerson** [havenprotocol/haven#1]
I cannot sync the wallet to the network, it says only 1 block available.

**Comment by texas-delaney** [comment]
Hi @NotYourTypicalPerson 
Haven is currently only running on a private test network until full release. 

To be notified of full release follow the subreddit for updates:
https://www.reddit.com/r/havenprotocol/

**Comment by havenprotocol** [comment]
Hi @NotYourTypicalPerson
Haven is currently only running on a private test network until full release.

To be notified of full release follow the subreddit for updates:
https://www.reddit.com/r/havenprotocol/
