### ISSUE TITLE
View Only

### ISSUE THREAD

**Issue by GAV1974** [havenprotocol/haven#13]
![dsc_0743](https://user-images.githubusercontent.com/38362545/39236052-504ebe68-4880-11e8-91f4-8b5aefe37c21.JPG)
Help please, how to get rid of the label "Only viewing". Assets in the purse are frozen, I can not make a withdrawal of funds.

**Comment by havenprotocol** [comment]
Restore the wallet from your mnemonic seed.

Go to settings, close wallet and when prompted click restore from seed. 

Please keep the github issues to code issues, these type of questions are better suited to the Discord channel.
