### ISSUE TITLE
Entering the password into the console does not work

### ISSUE THREAD

**Issue by aka-lex** [havenprotocol/haven#19]
In the console version of the wallet, the password does not work.
When you are prompted for a password, you can not type characters from the keyboard.
Also does not work the insertion of characters from the clipboard.
OS Win10x64

**Comment by aka-lex** [comment]
Everything is working. But "*" will not be superfluous.

**Comment by havenprotocol** [comment]
Passwords entered don't show typed characters in terminal. This is expected behaviour.
