### ISSUE TITLE
XMR Wallet port seeks XMR wallet file

### ISSUE THREAD

**Issue by Aris-Eng** [havenprotocol/haven#2]
The Haven Wallet, which I believe was ported from XMR, defaults to trying to open the XMR .keys wallet file, which is not saved in the Haven folder in Win10.
This occurs when the users has both XMR and XHV wallets installed in the same machine, and the result is that the XMR wallet file can be overwritten by XHV, assuming the XHV GUI wallet is installed second.

Admin havendev on discord has been notified of this.

For example of problem(s) caused, see this post I have made (before realizing what the root cause was): https://www.reddit.com/r/Monero/comments/87gtrp/another_back_up_everything_twice_story_that/

**Comment by aleqx** [comment]
Can confirm. it also doesn't matter where the wallet is saved, the XHV client reads the same registry entry at `HKCU\Software\monero-project\monero-core\wallet_path`.

This looks like clumsy/rushed forking ...

The web wallet also doesn't work (it works to sign-up, but not to log back in)

**Comment by havenprotocol** [comment]
Fixed in https://github.com/havenprotocol/haven-gui/commit/8806b88fd8f5154af0457b87e61a0f47975970fe
