### ISSUE TITLE
LWMA difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [havenprotocol/haven#3]
You have been suffering attacks because you have an old version of Masari's version of my LWMA. To eliminate teh problem, use [karbowanec's code](https://github.com/seredat/karbowanec/blob/32a64fb00ffcc51085232ef828414a7b1a072b82/src/CryptoNoteCore/Currency.cpp#L521-L579) and change your nodes' future time limit of 7200 seconds to 7xT.  I think your T=120 seconds.  Also, make your length 70 blocks.   It would be good to read the newest pseudocode of the [LWMA algorithm](https://github.com/zawy12/difficulty-algorithms/issues/3).

**Comment by havenprotocol** [comment]
Fully updated and improved on with the following commits:

73d1e9698d9a8d30bb72f643097a06c0e0dd6b44
fd9f3f2f2ee53d7dc81d14bdc406d9ef9271cec0
3fb80997dbda3f984d9547a7a26925a82eb09aba
2f4dfdeb954255b6fbcfa71a04c016f13eefaf13

**Comment by zawy12** [comment]
Awesome.  Thanks for taking the time to add comments for me.  What block will it fork on?

**Comment by havenprotocol** [comment]
38500

**Comment by zawy12** [comment]
I've looked at the code and the last 7300 blocks since the last fork to stop the timestamp attacks.  Everything looks good and I hope it's good enough that you'll never have to think about difficulty again.

**Comment by zawy12** [comment]
However, there's a slight difference in your results from mine.   Karbo's results look exactly like mine and Karbo's code looks exactly like yours.  So there is some discrepancy I'm trying to track down.

**Comment by zawy12** [comment]
I removed a couple of lines from the following, but look what this does:

```if (timestamps.size() > N) {
			timestamps.resize(N + 1);
		}
		size_t n = timestamps.size();
		assert(n <= DIFFICULTY_WINDOW_V2);
    if ( n < 6 ) { return  1; }
    else if (n < N+1) { N=n-1; }
```
Let's say timestamps.size begins = 300.  Then it is N+1.   Then n=N+1.   Then this means ```assert(n <= DIFFICULTY_WINDOW_V2);``` is always true after startup period.  This is my fault from not converting karbo code correctly  It was supposed to be changed to  ```assert(n <= DIFFICULTY_WINDOW_V2 + 1);``` or ```assert(n <= N+1);```  I thought assert was supposed to terminate.  In wownero which has the same code, N is N-1 which makes it look like the assert() reset n to N which then causes else if to exectute making N = N-1.  But it seems to be doing something different from wownero, eventhough the code is the same.  The algos are working good, but the small difference is result is worrying because the code is doing something it's not supposed to.

**Comment by zawy12** [comment]
This might be the problem:
```
#define DIFFICULTY_BLOCKS_COUNT_V2                         DIFFICULTY_WINDOW_V2
```
It needed to be  ```DIFFICULTY_WINDOW_V2+1``` because it's limiting the size of timestamps and cumulative_difficulties passed to LWMA.  It's only by accident that we had this line:
```else if (n < N+1) { N=n-1; }``` that was reducing N to N-1 on every block to prevent it from failing completely.  However, this change is not worth a fork.
