### ISSUE TITLE
No correct shares using linux

### ISSUE THREAD

**Issue by MahmoudAshraf97** [havenprotocol/haven#5]
I was using windows just fine and my gpus hash cryptonight at 3.8 kH/s and when i switched to cryptonight-heavy it dropped to 2kH/s despite using the same config and when i switched to linux it hashed at 3kH/s but no correct shares only errors, my gpus are not overclocked

**Comment by havenprotocol** [comment]
Closing as this is mining software configuration. I suggest you ask in the mining software you are using github issues or in Haven discord community.
