### ISSUE TITLE
Web wallet login doesn't work: "Error connecting to the backend. Can't login."

### ISSUE THREAD

**Issue by aleqx** [havenprotocol/haven#7]
I tried the web wallet. I signed up, got a new mnemonic and address, which I saved, then I closed the browser and tried to login to verify it works. It doesn't. Upon login with the mnemonic, I get:

`Error connecting to the backend. Can't login.`

**Comment by havenprotocol** [comment]
Closing due to unrelated. That error is server related and nothing to do with the Haven core.
